image: debian/testing
packages:
  - curl
  - rsync
  - rlwrap
  - default-jre
sources:
  - https://git.sr.ht/~codegouvfr/guide-awesome-codegouvfr
secrets:
  - bdd50953-add5-4ddb-9f34-9f0781900b7e
tasks:
  - install: |
      curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
      chmod +x linux-install.sh
      ./linux-install.sh
  - build: |
      cd guide-awesome-codegouvfr/
      clojure -M:js
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av guide-awesome-codegouvfr/resources/public/* web@code.gouv.fr:/home/web/websites/guide-awesome-codegouvfr/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
