# Default locale for UI strings
# Available UI languages: en, fr, de, sv
locale: "fr"

# Available themes: bulma, chota, dsfr
# You can set the theme on the command line with
# clj -X:set :theme bulma
theme: "dsfr"

# Customize UI strings
ui-strings:
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # redo:                 "Redo"
  # ok:                   "Okay"
  # contact-intro:        "Contact: "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
 title:    "Guide Awesome CodeGouvFr"
 subtitle: "Le logiciel libre publié par votre administration est-il *awesome* ? Faites le test."

# Website footer
footer:
 text:    "Site propulsé par [choices](https://git.sr.ht/~bzg/choices/) et maintenu par la [mission logiciels libres](https://code.gouv.fr) de la DINUM."
 contact:  "contact@code.gouv.fr"

# Allow users to send you emails with the summary?
mail-to: "contact@code.gouv.fr"

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
# Mostly useful for debugging
display-score-details: false

# Display the score with the highest value?
# Only when :as-top-result-display is set for each score
display-score-top-result: false

# In a branch of the tree, should the target node be set depending on
# the updated value of conditional-score-output?
conditional-navigation: false

# Some text message to always display after the score results
display-unconditionally: false

# Set initial variables to register scores.
score-variables:
  # "score-1" is a user-defined string
  score-1:
    # What to display when displaying score details:
    #display: "Votre score Awesome CodeGouvFr est de "
    # Initial value for score-1:
    value: 0
    # When you when the score message to use percent:
    as-percent: true
    # Max is needed for displaying percent:
    max: 10
    # Only needed when display-score-top-result is true
    #as-top-result-display: "1 wins :)"

# Set conditional output depending on scores.
conditional-score-output:
  # Cases are tested one by one.  The first case that matches is the
  # main score.  When case have a priority value, the matching case
  # with the highest priority is the main score.
  cas-1: # free-form condition name
    # priority: 2 # Use priority to matching order
    color: "is-success" # Bulma-based class names for the UI
    # notification.  Available values for colors are: is-success,
    # is-info, is-warning, is-danger.
    message: "Bravo, vous satisfaites %score-1% des critères !"
    # In score-variables, when :max is set and :as-percent is true,
    # then the score will be shown as a percentage.
    condition-1:
      score-1: 8 # This condition is met when score-1 is >= 2
  cas-2:
    color: "is-warning"
    message: "%score-1%, pas mal ! Rendez-vous sur notre [documentation](https://code.gouv.fr/documentation/#/publier) pour progresser."
    condition-1:
      score-1: 6 # This condition is met when score-1 is >= 1
  cas-3:
    color: "is-danger"
    message: "À %score-1%, il y a encore un peu de travail.  Rendez-vous sur la [doc](https://code.gouv.fr/documentation/#/publier) pour progresser."
    condition-1:
      score-1: 0 # This condition is met when score-1 is >= 0

# Mandatory configuration option
tree:
  - node:       "0"
    text:       "Un guide pour connaître le score **Awesome CodeGouvFr** de votre logiciel."
    home-page:  true
    no-summary: true
    help:       "Le score *Awesome CodeGouvFr* s'appuie sur [ces critères](https://github.com/codegouvfr/awesome-codegouvfr?tab=readme-ov-file#awesome-codegouvfr-score) proposés par la mission logiciels libres de la DINUM. Vous pouvez en savoir plus en lisant [notre entrée de blog](https://code.gouv.fr/fr/blog/awesome-codegouvfr-logiciels-libres-remarquables-de-ladministration/) et notre [documentation](https://code.gouv.fr/documentation/#/publier)."
    choices:
    - answer: "Commencer"
      goto:   "1"
      color:  "is-info"

  - node:       "1"
    progress:   "[0 10]"
    text:       "Y a-t-il une page web présentant le projet, en plus du dépôt de code source ?"
    start-page: true
    choices:
    - answer:  "Oui"
      summary: "Il y a une page web pour le projet, en plus du dépôt de code source."
      score:
        score-1:
          value: 1
      goto:    "2"
      color:   "is-success"
    - answer:  "Non"
      summary: "Il n’y a pas une page web pour le projet indépendante du dépôt de code source."
      color:   "is-danger"
      score:
        score-1:
          value: 0
      goto:    "2"

  - node:     "2"
    progress: "[1 10]"
    text:     "La dernière version date-t-elle de moins de six mois ?"
    choices:
    - answer:  "Oui"
      summary: "La derinière version date de moins de six mois."
      score:
        score-1:
          value: 1
      goto:    "3"
      color:   "is-success"
    - answer:  "Non"
      summary: "La dernière version date de plus de six mois."
      score:
        score-1:
          value: 0
      color:   "is-danger"
      goto:    "3"

  - node:     "3"
    progress: "[2 10]"
    text:     "Le dernier commit (toutes branches confondues) date-t-il de moins de six mois ?"
    choices:
    - answer:  "Oui"
      summary: "Oui, le dernier commit date de moins de six mois."
      goto: "4"
      color: "is-success"
      score:
        score-1:
          value: 1
    - answer:  "Non"
      summary: "Le dernier commit date d'il y a plus de six mois."
      score:
        score-1:
          value: 0
      color: "is-danger"
      goto: "4"

  - node: "4"
    progress: "[3 10]"
    text: "Le projet a-t-il un logo ?"
    choices:
    - answer: "Oui"
      summary: "Le projet a un logo."
      color: "is-success"
      goto: "5"
      score:
        score-1:
          value: 1
    - answer: "Non"
      summary: "Le projet n'a pas de logo."
      color: "is-danger"
      goto: "5"
      score:
        score-1:
          value: 0

  - node: "5"
    progress: "[4 10]"
    text: "Y a-t-il un fichier `ROADMAP.md` dans le dépôt pour décrire la feuille de route  ?"
    choices:
    - answer: "Oui"
      summary: "Il y a un fichier `ROADMAP.md` dans le dépôt pour décrire la feuille de route."
      color: "is-success"
      goto: "6"
      score:
        score-1:
                value: 1
    - answer: "Non"
      summary: "Il n’y a pas de fichier `ROADMAP.md` dans le dépôt."
      color: "is-danger"
      goto: "6"
      score:
         score-1:
          value: 0
  - node: "6"
    progress: "[5 10]"
    text: "Y a-t-il un fichier `AUTHORS.md` dans le dépôt avec la liste des auteurs ?"
    choices:
    - answer: "Oui"
      summary: "Il y a un fichier `AUTHORS.md` dans le dépôt.."
      color: "is-success"
      goto: "7"
      score:
        score-1:
          value: 1
    - answer: "Non"
      summary: "Il n’y a pas de fichier `AUTHORS.md` dans le dépôt.."
      color: "is-danger"
      goto: "7"
      score:
        score-1:
                value: 0

  - node: "7"
    progress: "[6 10]"
    text: "Y a-t-il un fichier `CONTRIBUTING.md` dans le dépôt expliquant comment contribuer ?"
    choices:
    - answer: "Oui"
      summary: "Il y a un fichier `CONTRIBUTING.md` dans le dépôt.."
      color: "is-success"
      goto: "8"
      score:
        score-1:
          value: 1
    - answer: "Non"
      summary: "Il n’y a pas de fichier `CONTRIBUTING.md` dans le dépôt.."
      color: "is-danger"
      goto: "8"
      score:
        score-1:
          value: 0

  - node: "8"
    progress: "[7 9]"
    text: "Y a-t-il un fichier `CHANGELOG.md` dans le dépôt avec la liste des changements principaux ?"
    choices:
    - answer: "Oui"
      summary: "Il y a un fichier `CHANGLOG.md` dans le dépôt.."
      color: "is-success"
      goto: "9"
      score:
        score-1:
          value: 1
    - answer: "Non"
      summary: "Il n’y a pas de fichier `CHANGELOG.md` dans le dépôt.."
      color: "is-danger"
      goto: "9"
      score:
        score-1:
          value: 0

  - node: "9"
    progress: "[8 10]"
    text: "Y a-t-il un fichier `CODE_OF_CONDUCT.md` dans le dépôt et un code de conduite pour le projet ?"
    choices:
    - answer: "Oui"
      summary: "Il y a un fichier `CODE_OF_CONDUCT.md` dans le dépôt.."
      color: "is-success"
      goto: "10"
      score:
        score-1:
          value: 1
    - answer: "Non"
      summary: "Il n’y a pas de fichier `CODE_OF_CONDUCT.md` dans le dépôt.."
      color: "is-danger"
      goto: "10"
      score:
        score-1:
          value: 0

  - node: "10"
    progress: "[9 10]"
    text: "Y a-t-il un fichier `GOVERNANCE.md` dans le dépôt présentant la gouvernance du projet ?"
    choices:
    - answer: "Oui"
      summary: "Il y a un fichier `GOVERNANCE.md` dans le dépôt.."
      color: "is-success"
      goto: "end"
      score:
        score-1:
          value: 1
    - answer: "Non"
      summary: "Il n’y a pas de fichier `GOVERNANCE.md` dans le dépôt.."
      color: "is-danger"
      goto: "end"
      score:
        score-1:
          value: 0

  - node: "end"
    progress: "[10 10]"
<<<<<<< HEAD
    text: "Terminé !"
=======
    text: "C'est terminé !  N'oubliez pas de consulter notre [documentation](https://code.gouv.fr/documentation/#/publier)"
>>>>>>> 87b1f58 (config.yml: Updates)
    done: true
